### ISSUE TITLE
Cannot improve accuracy even if even training data is very simple

### ISSUE THREAD

**Issue by relastle** [jostmey/MaxSnippetModel#1]
Thank you for publishing this wonderful software.

I would like to use this for my data.

Firstly, when we ran the program on the whole data, the accuracy did not improve from 50%,
so I tried to prepare a simple demonstration data.

I uploaded the demo data in zip format.

[demo_data.zip](https://github.com/jostmey/MaxSnippetModel/files/1824170/demo_data.zip)

That is, the structure of the directory when running the program is as follows.

```
├── bias.txt
├── data
│   ├── answers.csv
│   ├── sample_1_negative.csv
│   ├── sample_1_positive.csv
│   ├── sample_2_negative.csv
│   └── sample_2_positive.csv
├── dataplumbing.py
├── dataplumbing.pyc
├── dataplumbing_synthetic_data.py
├── lib
│   ├── aminoacid_factors.py
│   ├── atchley_factors.csv
│   ├── atchley_factors.py
│   ├── atchley_factors.pyc
│   ├── dna_factors.py
│   └── __pycache__
│       └── atchley_factors.cpython-36.pyc
├── lib_paths.py
├── lib_paths.pyc
├── LICENSE
├── model.py
├── model.pyc
├── __pycache__
│   ├── dataplumbing.cpython-36.pyc
│   ├── lib_paths.cpython-36.pyc
│   └── model.cpython-36.pyc
├── README.md
├── score.py
├── train.py
└── weights.txt
```

And then, run the command below.

```
python ./train.py
```

i think this demonstration is very easy one, but the accuracy does not improve.

Please let me know if something goes wrong.

**Comment by jostmey** [comment]
With your demo data, the negative samples contain the exact same list of sequences as the positive samples. In fact, I see no differences between the positive and negative samples.

The underlying assumption is that patients with a positive diagnosis will have antibodies (or T-cell receptors) difference from those with a negative diagnosis. Also, the approach will required many more samples than the two you provided.

I'm closing this ticket. Feel free to re-open one if you have more questions!

Cheers
Jared

**Comment by relastle** [comment]
Thank you very much for answering the question.
I was able to run the program not only with the demo-data but also with the data that I actually wanted to process.

Regards
Konishi
